version: '3'
services:
  #### Postgres DB Server
  postgres-db-server:
    container_name: postgres-db-server
    image: postgres:15.1
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      PGPORT: 5432
    ports:
      - "5432:5432"
    depends_on:
      - oidc-server-mock
#    command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
    volumes:
      - ./init/init_db.sql:/docker-entrypoint-initdb.d/10_init_db.sql
      - ./init/init_server.sh:/data/postgresql/init_server.sh
      - ./config_file:/data/postgresql/config_file
      - ./ssl_file:/data/postgresql/ssl_file
#      - ./ssl_file/server.crt:/var/lib/postgresql/server.crt
#      - ./ssl_file/server.key:/var/lib/postgresql/server.key
    networks:
      default:
        aliases:
          - postgres-db-server.internal